function countNumberedImageFiles_(imageFolder) {
  if (!imageFolder) return 0;

  var files = imageFolder.getFiles();
  var count = 0;
  while (files.hasNext()) {
    var file = files.next();
    if (/^\d+/.test(String(file.getName() || ''))) {
      count++;
    }
  }
  return count;
}

function getManualImageFileSummary_(imageFolder) {
  var summary = {
    validCount: 0,
    invalidCount: 0,
    invalidNames: [],
    totalCount: 0
  };

  if (!imageFolder) return summary;

  var files = imageFolder.getFiles();
  while (files.hasNext()) {
    var file = files.next();
    var fileName = String(file.getName() || '').trim();
    if (!fileName) continue;

    summary.totalCount++;
    if (/^\d+/.test(fileName)) {
      summary.validCount++;
    } else {
      summary.invalidCount++;
      summary.invalidNames.push(fileName);
    }
  }

  return summary;
}

function extractDriveFolderIdFromUrl_(folderUrl) {
  var match = String(folderUrl || '').match(/\/folders\/([^\/\?\#]+)/);
  return match ? match[1] : '';
}

function storeAutoGeneratedImageUrls_(sheet, rowIndex, image1Url, svgUrl) {
  if (!sheet || !rowIndex) return;
  if (image1Url) {
    sheet.getRange(rowIndex, 13).setValue(image1Url);
  }
  if (svgUrl) {
    sheet.getRange(rowIndex, 18).setValue(svgUrl);
  }
}

function getImageSourceFromControlRow_(controlRow) {
  if (!controlRow || !controlRow.values) {
    return '';
  }

  var imageSource = String(controlRow.values[9] || '').trim();
  if (imageSource === '자동생성') return '자동생성';
  if (imageSource === '직접업로드') return '직접업로드';
  return '';
}



function sanitizeFolderName_(title) {
  return String(title || '제목없음')
    .replace(/[\\\/:\*\?"<>\|#\[\]]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .substring(0, 80) || '제목없음';
}

function createImageFolderForPost_(title) {
  var parentFolder = DriveApp.getFolderById(IMAGE_PARENT_FOLDER_ID);
  var datePrefix = Utilities.formatDate(new Date(), 'Asia/Seoul', 'yyyyMMdd');
  var folderName = datePrefix + '_' + sanitizeFolderName_(title);
  var existingFolders = parentFolder.getFoldersByName(folderName);

  if (existingFolders.hasNext()) {
    return existingFolders.next();
  }

  return parentFolder.createFolder(folderName);
}

function buildPhotoGuideText_(finalData) {
  var photoGuides = finalData && finalData.photo_guides ? finalData.photo_guides : [];
  return photoGuides.join('\n');
}

function setImageSourceMode_(mode, message) {
  var spreadsheet = SpreadsheetApp.openById(CONTROL_SHEET_ID);
  var sheet = spreadsheet.getSheetByName(SHEET_NAME_MAIN);
  if (!sheet) {
    throw new Error('시트1을 찾을 수 없습니다.');
  }

  ensurePublishControlHeaders_(sheet);
  sheet.getRange(2, 10).setValue(mode);
  applyImageModeHeaderStyles_(sheet, mode);
  SpreadsheetApp.getUi().alert(message);
}

function processAutoImage_(finalData, imageFolder) {
  var controlRow = getPublishControlRow_(SpreadsheetApp.openById(CONTROL_SHEET_ID).getSheetByName(SHEET_NAME_MAIN));
  var storedOpenAiUrl = String((controlRow && controlRow.values ? controlRow.values[12] : '') || '').trim();
  var imagenPrompts = Array.isArray(finalData.imagen_prompts) ? finalData.imagen_prompts : [];
  var prompt1 = '';
  var primaryType = String(((finalData.content_type || {}).primary) || '').trim();
  var title = extractTitleFromContent_(finalData.content, finalData.baseName);
  var generatedImage1;
  var generatedImage2;

  for (var ip = 0; ip < imagenPrompts.length; ip++) {
    var item = imagenPrompts[ip] || {};
    var imageNo = Number(item.image_no);
    var promptText = String(item.prompt || item.text || '').trim();
    if (imageNo === 1 && promptText) prompt1 = promptText;
  }

  Logger.log('🧾 imagen_prompts.prompt1: ' + (prompt1 || '없음'));
  Logger.log('🧾 image2 SVG primaryType: ' + (primaryType || '없음'));

  if (!prompt1) {
    throw new Error('final_seo.json의 image1 prompt가 비어 있습니다. runGenerateOnly()를 다시 실행하세요.');
  }

  if (!storedOpenAiUrl) {
    throw new Error('M열 image1_url이 비어 있습니다. 메뉴에서 "🤖 OpenAI 이미지 생성"을 먼저 실행하세요.');
  }
  generatedImage1 = {
    fileName: 'image1_openai.png',
    mimeType: 'image/png',
    publicUrl: storedOpenAiUrl,
    responseCode: 200
  };
  Logger.log('✅ 저장된 image1 OpenAI URL 사용: ' + storedOpenAiUrl);

  var image2Svg = generateImage2AsSvg_(finalData.visual_strategy, primaryType, finalData.image2_table_data);
  var image2FileName = Utilities.formatDate(new Date(), 'Asia/Seoul', 'yyyyMMdd_HHmmss') + '_' +
    String(title || 'image').substring(0, 10).replace(/[^a-zA-Z0-9가-힣]/g, '_') + '_02.svg';
  var image2Blob = Utilities.newBlob(image2Svg, 'image/svg+xml', image2FileName);
  var image2Url = uploadBlobToGitHub_(image2Blob, image2FileName);
  generatedImage2 = {
    fileName: image2FileName,
    mimeType: 'image/svg+xml',
    publicUrl: image2Url,
    responseCode: 200
  };

  if (!generatedImage1 || !generatedImage2) {
    throw new Error('image1/image2 생성 실패: 2장의 이미지가 모두 생성되지 않았습니다.');
  }

  Logger.log('✅ image1 OpenAI + image2 SVG 생성 완료');
  Logger.log('🔗 01 URL: ' + generatedImage1.publicUrl);
  Logger.log('🔗 02.svg URL: ' + generatedImage2.publicUrl);

  return {
    mappedContent: mapGeneratedImageUrlsToPlaceholders_(finalData.content, [generatedImage1, generatedImage2]),
    generatedImages: [generatedImage1, generatedImage2]
  };
}

function processUnsplashImage_(finalData, imageFolder) {
  var title = extractTitleFromContent_(finalData.content, finalData.baseName);
  var placeholders = extractPhotoPlaceholders_(finalData.content);
  var downloadedPhotos = downloadUnsplashPhotosToFolder_(finalData.content, finalData, title, imageFolder);

  Logger.log('🧾 Unsplash 저장 결과 수: ' + downloadedPhotos.length);
  if (placeholders.length > 0 && downloadedPhotos.length === 0) {
    throw new Error('Unsplash 이미지 저장 0건: 플레이스홀더는 존재하지만 Drive 저장에 실패했습니다. 로그의 검색어/응답 코드를 확인하세요.');
  }

  return {
    mappedContent: mapPhotosToPlaceholders(finalData.content, imageFolder.getId(), finalData, title),
    downloadedPhotos: downloadedPhotos
  };
}

function processManualImage_(finalData, imageFolder) {
  var title = extractTitleFromContent_(finalData.content, finalData.baseName);
  return {
    mappedContent: mapManualPhotosToPlaceholders_(finalData.content, imageFolder.getId(), finalData, title)
  };
}

/**
 * 완전 통합 처리 함수 - 전처리 → SEO → 사진 매핑 → HTML 변환 → Blogger 발행
 */
function generateOpenAIImageOnly_(seoFileId) {
  var startTime = new Date().getTime();
  var spreadsheet = SpreadsheetApp.openById(CONTROL_SHEET_ID);
  var sheet = spreadsheet.getSheetByName(SHEET_NAME_MAIN);
  var statusRowIndex = 2;
  if (sheet) {
    ensurePublishControlHeaders_(sheet);
    var statusControlRow = getPublishControlRow_(sheet);
    statusRowIndex = statusControlRow && statusControlRow.rowIndex ? statusControlRow.rowIndex : 2;
  }
  if (!acquireExecutionFlag_(EXECUTION_FLAGS.OPENAI_IMAGE_RUNNING, 'generateOpenAIImageOnly_')) {
    updatePublishStatus_(sheet, statusRowIndex, '발행준비');
    SpreadsheetApp.getActiveSpreadsheet().toast('⚠️ OpenAI 이미지 생성이 이미 실행 중입니다.', '대산 블로그', 5);
    return {
      success: false,
      status: 'already_running'
    };
  }

  try {
    Logger.log('🤖 === OpenAI 이미지 단독 생성 시작 ===');
    updatePublishStatus_(sheet, statusRowIndex, '이미지생성중');

    var seoFile = getGeneratedSeoFileById_(seoFileId) || getLatestGeneratedSeoFile_();
    if (!seoFile) {
      throw new Error('_final_seo.json 파일을 찾지 못했습니다. runGenerateOnly()를 먼저 실행하세요.');
    }

    var finalData = JSON.parse(seoFile.getBlob().getDataAsString());
    var imagenPrompts = Array.isArray(finalData.imagen_prompts) ? finalData.imagen_prompts : [];
    var prompt1 = '';
    for (var i = 0; i < imagenPrompts.length; i++) {
      var item = imagenPrompts[i] || {};
      if (Number(item.image_no) === 1) {
        prompt1 = String(item.prompt || item.text || '').trim();
        break;
      }
    }

    if (!prompt1) {
      throw new Error('final_seo.json의 image1 prompt가 비어 있습니다. runGenerateOnly()를 다시 실행하세요.');
    }

    var title = extractTitleFromContent_(finalData.content, finalData.baseName);
    var imageFolder = createImageFolderForPost_(title);
    var openAiFileName = Utilities.formatDate(new Date(), 'Asia/Seoul', 'yyyyMMdd_HHmmss') + '_' +
      String(title || 'image').substring(0, 10).replace(/[^a-zA-Z0-9가-힣]/g, '_') + '_01_openai.png';
    var openAiImage1 = generateImageWithOpenAI_(prompt1, imageFolder.getId(), openAiFileName);

    if (!openAiImage1 || !openAiImage1.publicUrl) {
      throw new Error('OpenAI image1 생성 또는 업로드에 실패했습니다.');
    }

    if (!sheet) {
      throw new Error('시트1을 찾을 수 없습니다.');
    }
    ensurePublishControlHeaders_(sheet);
    var controlRow = getPublishControlRow_(sheet);
    var rowIndex = controlRow && controlRow.rowIndex ? controlRow.rowIndex : 2;
    writeToControlSheet_('image1_url', openAiImage1.publicUrl, rowIndex);

    updatePublishStatus_(sheet, rowIndex, '이미지생성완료');
    Logger.log('🖼️ image1 OpenAI URL 저장 완료: ' + openAiImage1.publicUrl);
    Logger.log('⏱️ generateOpenAIImageOnly_ 소요시간: ' + ((new Date().getTime() - startTime) / 1000).toFixed(1) + '초');
    SpreadsheetApp.getActiveSpreadsheet().toast('✅ OpenAI 이미지 생성 완료. M열 URL을 확인하세요.', '대산 블로그', 5);

    return {
      success: true,
      image1Url: openAiImage1.publicUrl
    };
  } catch (error) {
    Logger.log('❌ OpenAI 이미지 생성 오류: ' + error.message);
    updatePublishStatus_(sheet, statusRowIndex, '오류');
    SpreadsheetApp.getUi().alert('❌ OpenAI 이미지 생성 오류\n\n' + error.message);
    return {
      success: false,
      error: error.message
    };
  } finally {
    releaseExecutionFlag_(EXECUTION_FLAGS.OPENAI_IMAGE_RUNNING, 'generateOpenAIImageOnly_');
  }
}

function generateOpenAIImage() {
  generateOpenAIImageOnly_();
}

function openUploadFolder_() {
  var sheet = SpreadsheetApp.openById(CONTROL_SHEET_ID).getSheets()[0];
  var folderUrl = sheet.getRange('O2').getValue();

  if (!folderUrl) {
    SpreadsheetApp.getActiveSpreadsheet().toast(
      '⚠️ 업로드 폴더가 없습니다. 먼저 ① 글 생성을 실행하세요.', '대산 블로그', 5);
    return;
  }

  var folderId = extractDriveFolderIdFromUrl_(folderUrl);
  if (!folderId) {
    SpreadsheetApp.getUi().alert(
      '⚠️ 업로드 폴더 URL 형식이 올바르지 않습니다.\n\n' +
      String(folderUrl)
    );
    return;
  }

  try {
    var folder = DriveApp.getFolderById(folderId);
    folder.getName();
  } catch (error) {
    SpreadsheetApp.getUi().alert(
      '⚠️ 업로드 폴더에 접근할 수 없습니다.\n\n' +
      '폴더가 삭제되었거나 권한이 없을 수 있습니다.\n' +
      '먼저 ① 글 생성을 다시 실행해 새 폴더를 준비하세요.\n\n' +
      String(folderUrl)
    );
    return;
  }

  SpreadsheetApp.getUi().alert(
    '📁 사진 업로드 폴더\n\n' +
    folderUrl + '\n\n' +
    '위 링크를 복사하여 브라우저에서 열고\n' +
    'Q열 파일명 가이드를 참고하여 사진을 업로드하세요.'
  );
}

function getNextImagenFileName_(folder) {
  var files = folder.getFiles();
  var maxNumber = 0;

  while (files.hasNext()) {
    var file = files.next();
    var match = file.getName().match(/^(\d+)\.png$/i);
    if (!match) continue;
    var number = parseInt(match[1], 10);
    if (number > maxNumber) maxNumber = number;
  }

  return ('0' + (maxNumber + 1)).slice(-2) + '.png';
}

function generateImageWithOpenAI_(prompt, folderId, fileName) {
  try {
    var apiKey = PropertiesService.getScriptProperties().getProperty(PROP_KEYS.OPENAI_API_KEY);
    if (!apiKey) {
      throw new Error('OPENAI_API_KEY가 설정되지 않았습니다.');
    }

    var resolvedFileName = String(fileName || ('openai_' + new Date().getTime() + '.png')).trim();
    var payload = {
      model: 'gpt-image-2',
      prompt: prompt,
      n: 1,
      size: '1024x1024',
      quality: 'low'
    };

    Logger.log('🎨 === OpenAI 이미지 생성 시작 ===');
    Logger.log('🖼️ 저장 파일명: ' + resolvedFileName);
    Logger.log('📝 OpenAI 프롬프트(앞 200자): ' + String(prompt || '').substring(0, 200));

    var response = null;
    var responseCode = 0;
    var responseText = '';
    var maxRetries = 3;
    for (var attempt = 1; attempt <= maxRetries; attempt++) {
      response = UrlFetchApp.fetch('https://api.openai.com/v1/images/generations', {
        method: 'post',
        headers: {
          'Authorization': 'Bearer ' + apiKey,
          'Content-Type': 'application/json'
        },
        payload: JSON.stringify(payload),
        muteHttpExceptions: true
      });

      responseCode = response.getResponseCode();
      responseText = response.getContentText();
      Logger.log('📡 OpenAI 이미지 응답 코드: ' + responseCode + ' (시도 ' + attempt + '/' + maxRetries + ')');
      Logger.log('📝 OpenAI 이미지 응답(앞 200자): ' + responseText.substring(0, 200));

      if (responseCode >= 200 && responseCode < 300) {
        break;
      }

      if ((responseCode === 429 || responseCode === 502 || responseCode === 503) && attempt < maxRetries) {
        Logger.log('🔁 OpenAI 이미지 재시도 대기: ' + responseCode);
        Utilities.sleep(2000 * attempt);
        continue;
      }
      break;
    }

    if (responseCode < 200 || responseCode >= 300) {
      throw new Error('OpenAI 이미지 생성 실패: ' + responseText);
    }

    var responseJson = JSON.parse(response.getContentText());
    var imageBlob;

    if (responseJson.data && responseJson.data[0].b64_json) {
      var b64Data = responseJson.data[0].b64_json;
      imageBlob = Utilities.newBlob(
        Utilities.base64Decode(b64Data),
        'image/png',
        resolvedFileName
      );
      Logger.log('🧾 OpenAI 응답 형식: b64_json');
    } else if (responseJson.data && responseJson.data[0].url) {
      var imageUrl = responseJson.data[0].url;
      Logger.log('🧾 OpenAI 응답 형식: url');
      Logger.log('🔗 OpenAI 원본 이미지 URL: ' + imageUrl);
      imageBlob = UrlFetchApp.fetch(imageUrl).getBlob();
    } else {
      throw new Error('OpenAI 응답에 이미지 데이터가 없습니다.');
    }

    var base64Data = Utilities.base64Encode(imageBlob.getBytes());

    var publicUrl = uploadImageToGitHub_(base64Data, resolvedFileName);
    Logger.log('✅ OpenAI 이미지 GitHub 업로드 성공: ' + resolvedFileName);
    Logger.log('🔗 OpenAI 이미지 URL: ' + publicUrl);

    return {
      fileName: resolvedFileName,
      mimeType: 'image/png',
      publicUrl: publicUrl,
      responseCode: responseCode
    };
  } catch (error) {
    Logger.log('❌ generateImageWithOpenAI_ 오류: ' + error.message);
    Logger.log('❌ generateImageWithOpenAI_ 스택: ' + error.stack);
    return null;
  }
}

function uploadImageToGitHub_(base64Data, fileName) {
  var githubToken = getGithubToken_();
  var resolvedFileName = String(fileName || ('image_' + new Date().getTime() + '.png')).trim();
  var normalizedBase64 = String(base64Data || '').trim();
  var dataUriMatch = normalizedBase64.match(/^data:([^;]+);base64,(.+)$/);
  var apiUrl = 'https://api.github.com/repos/kangHo-Jun/Blog/contents/images/' + encodeURIComponent(resolvedFileName);

  if (!githubToken) {
    throw new Error('GITHUB_TOKEN이 설정되지 않았습니다. Properties Service에 저장하세요.');
  }

  if (!normalizedBase64) {
    throw new Error('업로드할 base64 이미지 데이터가 비어 있습니다.');
  }

  if (dataUriMatch) {
    normalizedBase64 = dataUriMatch[2] || '';
  }

  if (!normalizedBase64) {
    throw new Error('정규화 후 base64 이미지 데이터가 비어 있습니다.');
  }

  var existingResponse = UrlFetchApp.fetch(apiUrl, {
    method: 'get',
    headers: {
      Authorization: 'Bearer ' + githubToken,
      Accept: 'application/vnd.github+json'
    },
    muteHttpExceptions: true
  });
  var existingCode = existingResponse.getResponseCode();
  var existingText = existingResponse.getContentText();
  var payload = {
    message: 'Add blog image ' + resolvedFileName,
    content: normalizedBase64
  };

  if (existingCode === 200) {
    var existingData = JSON.parse(existingText);
    if (existingData && existingData.sha) {
      payload.sha = existingData.sha;
    }
  } else if (existingCode !== 404) {
    if (existingCode === 401 || existingCode === 403) {
      throw new Error('GitHub 토큰 권한 또는 만료 문제: ' + existingText);
    }
    throw new Error('GitHub 기존 파일 확인 실패: ' + existingText);
  }

  var response = UrlFetchApp.fetch(apiUrl, {
    method: 'put',
    contentType: 'application/json',
    payload: JSON.stringify(payload),
    headers: {
      Authorization: 'Bearer ' + githubToken,
      Accept: 'application/vnd.github+json'
    },
    muteHttpExceptions: true
  });
  var responseCode = response.getResponseCode();
  var responseText = response.getContentText();

  Logger.log('📡 GitHub 업로드 응답 코드: ' + responseCode);
  Logger.log('📝 GitHub 업로드 응답(앞 200자): ' + responseText.substring(0, 200));

  if (responseCode < 200 || responseCode >= 300) {
    if (responseCode === 401 || responseCode === 403) {
      throw new Error('GitHub 업로드 실패: 토큰 권한 또는 만료 문제 - ' + responseText);
    }
    if (responseCode === 413 || responseCode === 422) {
      throw new Error('GitHub 업로드 실패: 파일 크기 또는 요청 데이터 문제 - ' + responseText);
    }
    throw new Error('GitHub 업로드 실패: ' + responseText);
  }

  return 'https://raw.githubusercontent.com/kangHo-Jun/Blog/main/images/' + encodeURIComponent(resolvedFileName);
}

function uploadBlobToGitHub_(blob, fileName) {
  if (!blob) {
    throw new Error('업로드할 Blob이 비어 있습니다.');
  }
  var base64Data = Utilities.base64Encode(blob.getBytes());
  return uploadImageToGitHub_(base64Data, fileName);
}

function verifyImageUrlRenders_(url) {
  if (!url) {
    return {
      success: false,
      error: 'URL이 비어 있습니다.'
    };
  }

  try {
    var response = UrlFetchApp.fetch(url, {
      method: 'get',
      muteHttpExceptions: true
    });
    var responseCode = response.getResponseCode();
    var headers = response.getAllHeaders();
    var contentType = String((headers['Content-Type'] || headers['content-type'] || '')).toLowerCase();

    Logger.log('🧪 이미지 URL 검증 코드: ' + responseCode + ' / ' + url);
    Logger.log('🧪 이미지 URL 검증 content-type: ' + contentType);

    return {
      success: responseCode >= 200 && responseCode < 300 && contentType.indexOf('image/') === 0,
      responseCode: responseCode,
      contentType: contentType,
      url: url
    };
  } catch (error) {
    Logger.log('❌ 이미지 URL 검증 오류: ' + error.message);
    return {
      success: false,
      error: error.message,
      url: url
    };
  }
}

function extractImageUrlsFromHtml_(html) {
  var urls = [];
  var seen = {};
  var regex = /<img[^>]+src="([^"]+)"/gi;
  var match;

  while ((match = regex.exec(String(html || '')))) {
    var url = String(match[1] || '').trim();
    if (!url || seen[url]) continue;
    seen[url] = true;
    urls.push(url);
  }

  return urls;
}

function verifyPublishedImageUrls_(imageUrls) {
  var urls = Array.isArray(imageUrls) ? imageUrls : [];
  var results = [];
  var failed = [];

  for (var i = 0; i < urls.length; i++) {
    var result = verifyImageUrlRenders_(urls[i]);
    results.push(result);
    if (!result.success) {
      failed.push(result);
    }
  }

  Logger.log('🧪 이미지 URL 검증 대상 수: ' + urls.length);
  Logger.log('🧪 이미지 URL 검증 실패 수: ' + failed.length);

  return {
    total: urls.length,
    failedCount: failed.length,
    success: failed.length === 0,
    results: results,
    failed: failed
  };
}

function verifyBloggerPostImageRendering_(postUrl, expectedImageUrls) {
  if (!postUrl) {
    return {
      success: false,
      error: '게시 URL이 비어 있습니다.'
    };
  }

  try {
    var response = UrlFetchApp.fetch(postUrl, {
      method: 'get',
      muteHttpExceptions: true
    });
    var responseCode = response.getResponseCode();
    var html = response.getContentText() || '';
    var renderedImageUrls = extractImageUrlsFromHtml_(html);
    var expected = Array.isArray(expectedImageUrls) ? expectedImageUrls : [];
    var missing = [];

    for (var i = 0; i < expected.length; i++) {
      if (renderedImageUrls.indexOf(expected[i]) === -1) {
        missing.push(expected[i]);
      }
    }

    Logger.log('🧪 Blogger 게시 HTML 검증 코드: ' + responseCode + ' / ' + postUrl);
    Logger.log('🧪 Blogger 게시 HTML img 수: ' + renderedImageUrls.length);
    if (missing.length > 0) {
      Logger.log('⚠️ Blogger 게시 HTML 누락 이미지 수: ' + missing.length);
    }

    return {
      success: responseCode >= 200 && responseCode < 300 && renderedImageUrls.length > 0 && missing.length === 0,
      responseCode: responseCode,
      postUrl: postUrl,
      renderedCount: renderedImageUrls.length,
      expectedCount: expected.length,
      missing: missing,
      renderedImageUrls: renderedImageUrls
    };
  } catch (error) {
    Logger.log('❌ Blogger 게시 HTML 검증 오류: ' + error.message);
    return {
      success: false,
      error: error.message,
      postUrl: postUrl
    };
  }
}

/**
 * [신규] v7 HTML 전체 파이프라인 - 전처리부터 HTML 저장까지
 */
function mapPhotosToPlaceholders(docContent, imageFolderId, finalData, title) {
  if (!docContent) return "";

  try {
    if (!imageFolderId) {
      Logger.log("⚠️ imageFolderId가 없어 Unsplash 자동 검색으로 전환합니다.");
      return mapUnsplashPhotosToPlaceholders_(docContent, finalData, title);
    }

    // 1. Drive 폴더 접근
    var folder = DriveApp.getFolderById(imageFolderId);
    var files = folder.getFiles();
    var photoFiles = [];

    // 2. 파일 수집 (숫자로 시작하는 파일 필터링)
    while (files.hasNext()) {
      var file = files.next();
      var fileName = file.getName();
      if (/^\d+/.test(fileName)) {
        photoFiles.push(file);
      }
    }

    // 3. 파일 이름 번호 순 정렬 (01, 02, 03...)
    photoFiles.sort(function(a, b) {
      var numA = parseInt(a.getName().match(/^\d+/)[0], 10);
      var numB = parseInt(b.getName().match(/^\d+/)[0], 10);
      return numA - numB;
    });

    if (photoFiles.length === 0) {
      Logger.log("⚠️ 경고: 폴더에 매핑할 사진 파일이 없습니다. Unsplash 자동 검색으로 전환합니다.");
      return mapUnsplashPhotosToPlaceholders_(docContent, finalData, title);
    }

    // 4. 본문 내 홀더 추출 및 교체
    var resultBody = docContent;
    var mappedCount = 0;
    var unmappedHolders = [];
    
    // [사진N] 형태의 모든 홀더 탐색
    var placeholderMatches = docContent.match(/\[사진\s*\d+(?:\s*:[^\]]*)?\]/g) || [];
    // 중복 제거된 고유 홀더 목록 (V8 엔진 기준)
    var uniqueHolders = Array.from(new Set(placeholderMatches)).sort(function(a, b) {
      var numA = parseInt(a.match(/\d+/)[0]);
      var numB = parseInt(b.match(/\d+/)[0]);
      return numA - numB;
    });

    uniqueHolders.forEach(function(holder) {
      var photoNum = parseInt(holder.match(/\d+/)[0], 10);
      var fileIndex = photoNum - 1; // 1번 사진은 index 0

      if (fileIndex >= 0 && fileIndex < photoFiles.length) {
        var file = photoFiles[fileIndex];
        var photoDescription = extractPhotoDescriptionFromHolder_(holder);
        
        // 파일을 링크가 있는 모든 사용자에게 공개 (보기 권한)
        try {
          file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
          
          // 직링크 URL 생성 (Google Drive 고유 ID 활용)
          var photoUrl = "https://lh3.googleusercontent.com/d/" + file.getId();
          
          // 본문 내 모든 해당 홀더 교체
          var escapedHolder = holder.replace(/[\[\]]/g, "\\$&"); // [ ] 특수문자 탈출 처리
          var regex = new RegExp(escapedHolder, "g");
          resultBody = resultBody.replace(regex, buildBloggerImageToken_(photoUrl, photoDescription));
          mappedCount++;
        } catch (shareError) {
          Logger.log("❌ 권한 설정 실패: " + file.getName() + " (" + shareError.message + ")");
          unmappedHolders.push(holder);
        }
      } else {
        var fallbackResult = searchUnsplashPhoto_(buildUnsplashKeywordFromHolder_(holder, finalData, title));
        if (fallbackResult.imageUrl) {
          var fallbackDescription = extractPhotoDescriptionFromHolder_(holder);
          var escapedHolder = holder.replace(/[\[\]]/g, "\\$&");
          var regex = new RegExp(escapedHolder, "g");
          resultBody = resultBody.replace(regex, buildBloggerImageToken_(fallbackResult.imageUrl, fallbackDescription));
          mappedCount++;
          Logger.log("🧠 폴더 사진 부족 → Unsplash 대체 적용: " + fallbackResult.creditText);
        } else {
          unmappedHolders.push(holder);
        }
      }
    });

    // 5. 남은 [사진 N: ...] 텍스트 전체 제거 (매핑 여부 관계없이)
    var beforeClean = resultBody;
    resultBody = resultBody.replace(/\[사진\s*\d+[^\]]*\]/g, '');
    var removedCount = (beforeClean.match(/\[사진\s*\d+[^\]]*\]/g) || []).length;

    // 6. 처리 로그 출력
    Logger.log("✅ 사진 매핑 완료: 총 " + mappedCount + "개 교체됨");
    if (removedCount > 0) {
      Logger.log("🗑️ 사진 가이드 텍스트 제거: " + removedCount + "개 ([사진 N: ...] 형식)");
    }
    if (unmappedHolders.length > 0) {
      Logger.log("⚠️ 미매핑 홀더 (" + unmappedHolders.length + "개): " + unmappedHolders.join(", "));
    }

    return resultBody;

  } catch (error) {
    Logger.log("❌ 오류 발생 (mapPhotosToPlaceholders): " + error.message);
    Logger.log("❌ mapPhotosToPlaceholders 스택: " + error.stack);
    return docContent; // 실패 시 원본 본문 반환
  }
}

function mapManualPhotosToPlaceholders_(docContent, imageFolderId, finalData, title) {
  if (!docContent) return "";

  try {
    if (!imageFolderId) {
      Logger.log("⚠️ 직접업로드 매핑 실패: imageFolderId가 없습니다.");
      return docContent.replace(/\[사진\s*\d+[^\]]*\]/g, '');
    }

    var folder = DriveApp.getFolderById(imageFolderId);
    var files = folder.getFiles();
    var photoFiles = [];

    while (files.hasNext()) {
      var file = files.next();
      var fileName = file.getName();
      if (/^\d+/.test(fileName)) {
        photoFiles.push(file);
      }
    }

    photoFiles.sort(function(a, b) {
      var numA = parseInt(a.getName().match(/^\d+/)[0], 10);
      var numB = parseInt(b.getName().match(/^\d+/)[0], 10);
      return numA - numB;
    });

    var resultBody = docContent;
    var mappedCount = 0;
    var unmappedHolders = [];
    var placeholderMatches = docContent.match(/\[사진\s*\d+(?:\s*:[^\]]*)?\]/g) || [];
    var uniqueHolders = Array.from(new Set(placeholderMatches)).sort(function(a, b) {
      var numA = parseInt(a.match(/\d+/)[0], 10);
      var numB = parseInt(b.match(/\d+/)[0], 10);
      return numA - numB;
    });

    uniqueHolders.forEach(function(holder) {
      var photoNum = parseInt(holder.match(/\d+/)[0], 10);
      var fileIndex = photoNum - 1;

      if (fileIndex >= 0 && fileIndex < photoFiles.length) {
        var file = photoFiles[fileIndex];
        var photoDescription = extractPhotoDescriptionFromHolder_(holder);

        try {
          file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
          var photoUrl = "https://lh3.googleusercontent.com/d/" + file.getId();
          var escapedHolder = holder.replace(/[\[\]]/g, "\\$&");
          var regex = new RegExp(escapedHolder, "g");
          resultBody = resultBody.replace(regex, buildBloggerImageToken_(photoUrl, photoDescription));
          mappedCount++;
        } catch (shareError) {
          Logger.log("❌ 직접업로드 권한 설정 실패: " + file.getName() + " (" + shareError.message + ")");
          unmappedHolders.push(holder);
        }
      } else {
        unmappedHolders.push(holder);
      }
    });

    var beforeClean = resultBody;
    resultBody = resultBody.replace(/\[사진\s*\d+[^\]]*\]/g, '');
    var removedCount = (beforeClean.match(/\[사진\s*\d+[^\]]*\]/g) || []).length;

    Logger.log("✅ 직접업로드 사진 매핑 완료: 총 " + mappedCount + "개 교체됨");
    if (removedCount > 0) {
      Logger.log("🗑️ 직접업로드 플레이스홀더 제거: " + removedCount + "개");
    }
    if (unmappedHolders.length > 0) {
      Logger.log("⚠️ 직접업로드 미매핑 홀더 (" + unmappedHolders.length + "개): " + unmappedHolders.join(", "));
    }

    return resultBody;
  } catch (error) {
    Logger.log("❌ 오류 발생 (mapManualPhotosToPlaceholders_): " + error.message);
    Logger.log("❌ mapManualPhotosToPlaceholders_ 스택: " + error.stack);
    return docContent.replace(/\[사진\s*\d+[^\]]*\]/g, '');
  }
}



function extractPhotoDescriptionFromHolder_(holder) {
  var descriptionMatch = String(holder || '').match(/:\s*([^\]]+)/);
  return descriptionMatch ? descriptionMatch[1].trim() : '관련 이미지';
}

function buildBloggerImageToken_(url, description) {
  return '[[IMG::' + encodeURIComponent(String(url || '')) + '::' + encodeURIComponent(String(description || '관련 이미지')) + ']]';
}

function parseBloggerImageToken_(line) {
  var match = String(line || '').match(/^\[\[IMG::(.+?)::(.+?)\]\]$/);
  if (!match) return null;

  return {
    url: decodeURIComponent(match[1]),
    description: decodeURIComponent(match[2])
  };
}

function mapGeneratedImageUrlsToPlaceholders_(docContent, generatedImages) {
  if (!docContent) return '';

  var resultBody = docContent;
  var mappedCount = 0;
  var placeholderMatches = docContent.match(/\[사진\s*\d+(?:\s*:[^\]]*)?\]/g) || [];
  var uniqueHolders = Array.from(new Set(placeholderMatches)).sort(function(a, b) {
    var numA = parseInt(a.match(/\d+/)[0], 10);
    var numB = parseInt(b.match(/\d+/)[0], 10);
    return numA - numB;
  });

  for (var i = 0; i < uniqueHolders.length; i++) {
    var holder = uniqueHolders[i];
    var imageIndex = parseInt(holder.match(/\d+/)[0], 10) - 1;
    var generated = generatedImages && generatedImages[imageIndex];
    var publicUrl = generated && generated.publicUrl ? generated.publicUrl : '';
    var photoDescription = extractPhotoDescriptionFromHolder_(holder);

    if (!publicUrl) {
      continue;
    }

    var escapedHolder = holder.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp(escapedHolder, "g");
    resultBody = resultBody.replace(regex, buildBloggerImageToken_(publicUrl, photoDescription));
    mappedCount++;
  }

  resultBody = resultBody.replace(/\[사진\s*\d+[^\]]*\]/g, '');
  Logger.log('✅ 생성 이미지 URL 매핑 완료: 총 ' + mappedCount + '개 교체됨');
  return resultBody;
}

var BUILDING_KEYWORD_MAP = {
  'gypsum': 'drywall installation gypsum board',
  'insulation': 'building insulation material',
  'window': 'modern window frame interior',
  'air': 'indoor air quality healthy home',
  'eco': 'eco friendly building material',
  'construction': 'home renovation construction worker',
  'wall': 'interior wall construction',
  'renovation': 'home renovation interior',
  'material': 'construction building material',
  'indoor': 'healthy indoor living space'
};

function extractEnglishPlaceholderKeyword_(holder) {
  var descriptionMatch = String(holder || '').match(/:\s*([^\]]+)/);
  var description = descriptionMatch ? descriptionMatch[1].trim() : '';

  return description
    .replace(/[^a-zA-Z\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function buildUnsplashKeywordFromHolder_(holder, finalData, title) {
  var englishKeyword = extractEnglishPlaceholderKeyword_(holder);

  for (var key in BUILDING_KEYWORD_MAP) {
    if (englishKeyword.indexOf(key) !== -1) {
      Logger.log('🧭 키워드 매핑 적용: ' + englishKeyword + ' -> ' + BUILDING_KEYWORD_MAP[key]);
      return BUILDING_KEYWORD_MAP[key];
    }
  }

  Logger.log('🧭 키워드 원문 사용: ' + englishKeyword);
  return englishKeyword;
}

function searchUnsplashPhoto_(keyword) {
  var accessKey = getUnsplashKey_();
  if (!accessKey) {
    throw new Error('UNSPLASH_ACCESS_KEY가 설정되지 않았습니다. 자동생성 사용 전에 Properties Service에 키를 저장하세요.');
  }

  var apiUrl = 'https://api.unsplash.com/search/photos?query=' +
    encodeURIComponent(keyword) +
    '&page=1&per_page=1&orientation=landscape&content_filter=high';

  Logger.log('🔎 Unsplash 검색어: ' + keyword);
  var response = UrlFetchApp.fetch(apiUrl, {
    method: 'get',
    headers: {
      Authorization: 'Client-ID ' + accessKey,
      'Accept-Version': 'v1'
    },
    muteHttpExceptions: true
  });

  var responseCode = response.getResponseCode();
  var responseText = response.getContentText();
  Logger.log('📡 Unsplash 응답 코드: ' + responseCode);
  Logger.log('📝 Unsplash 응답 미리보기(앞 120자): ' + responseText.substring(0, 120));

  if (responseCode < 200 || responseCode >= 300) {
    throw new Error('Unsplash API 호출 실패: ' + responseText);
  }

  var responseData = JSON.parse(responseText);
  var photo = responseData && responseData.results && responseData.results.length > 0
    ? responseData.results[0]
    : null;
  var imageUrl = photo && photo.urls ? (photo.urls.regular || photo.urls.full || photo.urls.small || '') : '';
  var photographer = photo && photo.user && photo.user.name ? photo.user.name : '';
  var creditText = photographer ? ('Photo by ' + photographer + ' on Unsplash') : 'Unsplash 출처 정보 없음';

  return {
    responseCode: responseCode,
    imageUrl: imageUrl,
    creditText: creditText,
    raw: photo
  };
}

function extractPhotoPlaceholders_(docContent) {
  var placeholderMatches = String(docContent || '').match(/\[사진\s*\d+(?:\s*:[^\]]*)?\]/g) || [];
  return Array.from(new Set(placeholderMatches)).sort(function(a, b) {
    var numA = parseInt(a.match(/\d+/)[0], 10);
    var numB = parseInt(b.match(/\d+/)[0], 10);
    return numA - numB;
  });
}

function clearAutoGeneratedImageFiles_(folder) {
  if (!folder) return;

  var files = folder.getFiles();
  while (files.hasNext()) {
    var file = files.next();
    if (/^\d+\.(jpg|jpeg|png)$/i.test(file.getName())) {
      file.setTrashed(true);
    }
  }
}

function downloadUnsplashPhotosToFolder_(docContent, finalData, title, folder) {
  if (!folder) {
    throw new Error('Unsplash 저장 대상 Drive 폴더가 없습니다.');
  }

  var placeholders = extractPhotoPlaceholders_(docContent);
  var downloaded = [];
  var queryCache = {};

  Logger.log('🧠 Unsplash Drive 저장 시작');
  Logger.log('📁 대상 폴더: ' + folder.getName() + ' (' + folder.getId() + ')');
  Logger.log('📋 다운로드 대상 플레이스홀더 수: ' + placeholders.length);

  clearAutoGeneratedImageFiles_(folder);

  for (var i = 0; i < placeholders.length; i++) {
    var holder = placeholders[i];
    var query = buildUnsplashKeywordFromHolder_(holder, finalData, title);
    Logger.log('🔽 다운로드 시도: ' + holder + ' / query=' + query);
    var searchResult = queryCache[query];

    if (searchResult === undefined) {
      searchResult = query ? searchUnsplashPhoto_(query) : { imageUrl: '', creditText: '' };
      queryCache[query] = searchResult;
    }

    if (!searchResult.imageUrl) {
      Logger.log('⚠️ Unsplash 이미지 검색 실패: ' + holder);
      continue;
    }

    var imageResponse = UrlFetchApp.fetch(searchResult.imageUrl, {
      method: 'get',
      muteHttpExceptions: true
    });
    var imageCode = imageResponse.getResponseCode();
    Logger.log('📡 이미지 다운로드 응답 코드: ' + imageCode + ' / ' + holder);

    if (imageCode < 200 || imageCode >= 300) {
      Logger.log('❌ Unsplash 이미지 다운로드 실패 (' + imageCode + '): ' + holder);
      continue;
    }

    var imageNumber = parseInt(holder.match(/\d+/)[0], 10);
    var fileName = ('0' + imageNumber).slice(-2) + '.jpg';
    var imageBlob = imageResponse.getBlob().setName(fileName);
    var savedFile = folder.createFile(imageBlob);
    savedFile.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);

    downloaded.push({
      placeholder: holder,
      fileName: fileName,
      fileId: savedFile.getId(),
      creditText: searchResult.creditText
    });

    Logger.log('💾 Unsplash 이미지 저장 완료: ' + fileName + ' / ' + searchResult.creditText);
  }

  Logger.log('✅ Unsplash Drive 저장 완료: ' + downloaded.length + '개');
  return downloaded;
}

function mapUnsplashPhotosToPlaceholders_(docContent, finalData, title) {
  if (!docContent) return '';

  try {
    var resultBody = docContent;
    var mappedCount = 0;
    var unmappedHolders = [];
    var queryCache = {};
    var placeholderMatches = docContent.match(/\[사진\s*\d+(?:\s*:[^\]]*)?\]/g) || [];
    var uniqueHolders = Array.from(new Set(placeholderMatches)).sort(function(a, b) {
      var numA = parseInt(a.match(/\d+/)[0], 10);
      var numB = parseInt(b.match(/\d+/)[0], 10);
      return numA - numB;
    });

    for (var i = 0; i < uniqueHolders.length; i++) {
      var holder = uniqueHolders[i];
      var query = buildUnsplashKeywordFromHolder_(holder, finalData, title);
      var searchResult = queryCache[query];

      if (searchResult === undefined) {
        searchResult = query ? searchUnsplashPhoto_(query) : { imageUrl: '', creditText: '' };
        queryCache[query] = searchResult;
      }

      if (searchResult.imageUrl) {
        var photoDescription = extractPhotoDescriptionFromHolder_(holder);
        var escapedHolder = holder.replace(/[\[\]]/g, "\\$&");
        var regex = new RegExp(escapedHolder, "g");
        resultBody = resultBody.replace(regex, buildBloggerImageToken_(searchResult.imageUrl, photoDescription));
        mappedCount++;
        Logger.log("🖼️ Unsplash 적용: " + searchResult.creditText);
      } else {
        unmappedHolders.push(holder);
      }
    }

    var beforeClean = resultBody;
    resultBody = resultBody.replace(/\[사진\s*\d+[^\]]*\]/g, '');
    var removedCount = (beforeClean.match(/\[사진\s*\d+[^\]]*\]/g) || []).length;

    Logger.log("✅ Unsplash 사진 매핑 완료: 총 " + mappedCount + "개 교체됨");
    if (removedCount > 0) {
      Logger.log("🗑️ Unsplash 사진 가이드 텍스트 제거: " + removedCount + "개");
    }
    if (unmappedHolders.length > 0) {
      Logger.log("⚠️ Unsplash 미매핑 홀더 (" + unmappedHolders.length + "개): " + unmappedHolders.join(", "));
    }

    return resultBody;
  } catch (error) {
    Logger.log("❌ 오류 발생 (mapUnsplashPhotosToPlaceholders_): " + error.message);
    Logger.log("❌ Unsplash 사진 매핑 스택: " + error.stack);
    return docContent;
  }
}

